name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Create ZIP file for release
        run: |
          cd custom_components/red_energy
          zip -r ../../red_energy.zip .
          cd ../..

      - name: Upload ZIP to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: red_energy.zip
          asset_name: red_energy.zip
          tag: ${{ github.ref }}
          overwrite: true
